/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */ export var styles = ['label[_ngcontent-%COMP%] {\n    display: inline-block;\n    width: 3em;\n    margin: .5em 0;\n    color: #607D8B;\n    font-weight: bold;\n}\n\ninput[_ngcontent-%COMP%] {\n    height: 2em;\n    font-size: 1em;\n    padding-left: .4em;\n}\n\nbutton[_ngcontent-%COMP%] {\n    margin-top: 20px;\n    font-family: Arial;\n    background-color: #eee;\n    border: none;\n    padding: 5px 10px;\n    border-radius: 4px;\n    cursor: pointer;\n    cursor: hand;\n}\n\nbutton[_ngcontent-%COMP%]:hover {\n    background-color: #cfd8dc;\n}\n\nbutton[_ngcontent-%COMP%]:disabled {\n    background-color: #eee;\n    color: #ccc;\n    cursor: auto;\n}'];
//# sourceMappingURL=hero-detail.component.css.shim.ngstyle.js.map