/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


export const styles:any[] = ['.search-result[_ngcontent-%COMP%] {\n    border-bottom: 1px solid gray;\n    border-left: 1px solid gray;\n    border-right: 1px solid gray;\n    width: 195px;\n    height: 16px;\n    padding: 5px;\n    background-color: white;\n    cursor: pointer;\n}\n\n.search-result[_ngcontent-%COMP%]:hover {\n    color: #eee;\n    background-color: #607D8B;\n}\n\n#search-box[_ngcontent-%COMP%] {\n    width: 200px;\n    height: 20px;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvYWxpL1JlcG9zaXRvcmllcy9hbmd1bGFyLXRvdXItb2YtaGVyb2VzL3NyYy9hcHAvaGVyby9oZXJvLXNlYXJjaC5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvYWxpL1JlcG9zaXRvcmllcy9hbmd1bGFyLXRvdXItb2YtaGVyb2VzL3NyYy9hcHAvaGVyby9oZXJvLXNlYXJjaC5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
