/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


export const styles:any[] = ['label[_ngcontent-%COMP%] {\n    display: inline-block;\n    width: 3em;\n    margin: .5em 0;\n    color: #607D8B;\n    font-weight: bold;\n}\n\ninput[_ngcontent-%COMP%] {\n    height: 2em;\n    font-size: 1em;\n    padding-left: .4em;\n}\n\nbutton[_ngcontent-%COMP%] {\n    margin-top: 20px;\n    font-family: Arial;\n    background-color: #eee;\n    border: none;\n    padding: 5px 10px;\n    border-radius: 4px;\n    cursor: pointer;\n    cursor: hand;\n}\n\nbutton[_ngcontent-%COMP%]:hover {\n    background-color: #cfd8dc;\n}\n\nbutton[_ngcontent-%COMP%]:disabled {\n    background-color: #eee;\n    color: #ccc;\n    cursor: auto;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvYWxpL1JlcG9zaXRvcmllcy9hbmd1bGFyLXRvdXItb2YtaGVyb2VzL3NyYy9hcHAvaGVyby9oZXJvLWRldGFpbC5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvYWxpL1JlcG9zaXRvcmllcy9hbmd1bGFyLXRvdXItb2YtaGVyb2VzL3NyYy9hcHAvaGVyby9oZXJvLWRldGFpbC5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
