/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


export const styles:any[] = ['h1[_ngcontent-%COMP%] {\n    font-size: 1.2em;\n    color: #999;\n    margin-bottom: 0;\n}\n\nh2[_ngcontent-%COMP%] {\n    font-size: 2em;\n    margin-top: 0;\n    padding-top: 0;\n}\n\nnav[_ngcontent-%COMP%]   a[_ngcontent-%COMP%] {\n    padding: 5px 10px;\n    text-decoration: none;\n    margin-top: 10px;\n    display: inline-block;\n    background-color: #eee;\n    border-radius: 4px;\n}\n\nnav[_ngcontent-%COMP%]   a[_ngcontent-%COMP%]:visited, a[_ngcontent-%COMP%]:link {\n    color: #607D8B;\n}\n\nnav[_ngcontent-%COMP%]   a[_ngcontent-%COMP%]:hover {\n    color: #039be5;\n    background-color: #CFD8DC;\n}\n\nnav[_ngcontent-%COMP%]   a.active[_ngcontent-%COMP%] {\n    color: #039be5;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvYWxpL1JlcG9zaXRvcmllcy9hbmd1bGFyLXRvdXItb2YtaGVyb2VzL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9hbGkvUmVwb3NpdG9yaWVzL2FuZ3VsYXItdG91ci1vZi1oZXJvZXMvc3JjL2FwcC9hcHAuY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
