/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from './dashboard.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '@angular/router';
import * as import3 from '@angular/common';
import * as import4 from '../hero/hero-search.component.ngfactory';
import * as import5 from '../../../app/hero/hero-search.service';
import * as import6 from '@angular/http';
import * as import7 from '../../../app/hero/hero-search.component';
import * as import8 from '../../../app/dashboard/dashboard.component';
import * as import9 from '../../../app/hero/hero.service';
const styles_DashboardComponent:any[] = [import0.styles];
export const RenderType_DashboardComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_DashboardComponent,
  data: {}
}
);
function View_DashboardComponent_1(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
      (l()(),import1.ɵeld(0,(null as any),(null as any),9,'a',[[
        'class',
        'col-1-4'
      ]
    ],[
      [
        1,
        'target',
        0
      ]
      ,
      [
        8,
        'href',
        4
      ]

    ]
      ,[[
        (null as any),
        'click'
      ]
    ],(v,en,$event) => {
      var ad:boolean = true;
      if (('click' === en)) {
        const pd_0:any = ((<any>import1.ɵnov(v,1).onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
        ad = (pd_0 && ad);
      }
      return ad;
    },(null as any),(null as any))),
    import1.ɵdid(335872,(null as any),0,import2.RouterLinkWithHref,[
      import2.Router,
      import2.ActivatedRoute,
      import3.LocationStrategy
    ]
      ,{routerLink: [
        0,
        'routerLink'
      ]
    },(null as any)),
    import1.ɵpad(2),
    (l()(),import1.ɵted((null as any),['\n        '])),
      (l()(),import1.ɵeld(0,(null as any),(null as any),4,'div',[[
        'class',
        'module hero'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n            '])),
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'h4',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),[
      '',
      ''
    ]
    )),
    (l()(),import1.ɵted((null as any),['\n        '])),
    (l()(),import1.ɵted((null as any),['\n    ']))
  ]
  ,(ck,v) => {
    const currVal_2:any = ck(v,2,0,'/detail',v.context.$implicit.id);
    ck(v,1,0,currVal_2);
  },(ck,v) => {
    const currVal_0:any = import1.ɵnov(v,1).target;
    const currVal_1:any = import1.ɵnov(v,1).href;
    ck(v,0,0,currVal_0,currVal_1);
    const currVal_3:any = v.context.$implicit.name;
    ck(v,7,0,currVal_3);
  });
}
export function View_DashboardComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'h3',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['Top Heroes'])),
    (l()(),import1.ɵted((null as any),['\n'])),
      (l()(),import1.ɵeld(0,(null as any),(null as any),4,'div',[[
        'class',
        'grid grid-pad'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n    '])),
    (l()(),import1.ɵand(8388608,(null as any),(null as any),1,(null as any),View_DashboardComponent_1)),
    import1.ɵdid(401408,(null as any),0,import3.NgForOf,[
      import1.ViewContainerRef,
      import1.TemplateRef,
      import1.IterableDiffers
    ]
      ,{ngForOf: [
        0,
        'ngForOf'
      ]
    },(null as any)),
    (l()(),import1.ɵted((null as any),['\n'])),
    (l()(),import1.ɵted((null as any),['\n'])),
    (l()(),import1.ɵeld(0,(null as any),(null as any),2,'hero-search',([] as any[]),(null as any),(null as any),(null as any),import4.View_HeroSearchComponent_0,import4.RenderType_HeroSearchComponent)),
    import1.ɵprd(256,(null as any),import5.HeroSearchService,import5.HeroSearchService,[import6.Http]),
    import1.ɵdid(57344,(null as any),0,import7.HeroSearchComponent,[
      import5.HeroSearchService,
      import2.Router
    ]
    ,(null as any),(null as any))
  ]
  ,(ck,v) => {
    var co:import8.DashboardComponent = v.component;
    const currVal_0:any = co.heroes;
    ck(v,6,0,currVal_0);
    ck(v,11,0);
  },(null as any));
}
function View_DashboardComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'dashboard',([] as any[]),(null as any),(null as any),(null as any),View_DashboardComponent_0,RenderType_DashboardComponent)),
    import1.ɵdid(57344,(null as any),0,import8.DashboardComponent,[import9.HeroService],(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const DashboardComponentNgFactory:import1.ComponentFactory<import8.DashboardComponent> = import1.ɵccf('dashboard',import8.DashboardComponent,View_DashboardComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvYWxpL1JlcG9zaXRvcmllcy9hbmd1bGFyLXRvdXItb2YtaGVyb2VzL3NyYy9hcHAvZGFzaGJvYXJkL2Rhc2hib2FyZC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9hbGkvUmVwb3NpdG9yaWVzL2FuZ3VsYXItdG91ci1vZi1oZXJvZXMvc3JjL2FwcC9kYXNoYm9hcmQvZGFzaGJvYXJkLmNvbXBvbmVudC50cyIsIm5nOi8vL2hvbWUvYWxpL1JlcG9zaXRvcmllcy9hbmd1bGFyLXRvdXItb2YtaGVyb2VzL3NyYy9hcHAvZGFzaGJvYXJkL2Rhc2hib2FyZC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvYWxpL1JlcG9zaXRvcmllcy9hbmd1bGFyLXRvdXItb2YtaGVyb2VzL3NyYy9hcHAvZGFzaGJvYXJkL2Rhc2hib2FyZC5jb21wb25lbnQudHMuRGFzaGJvYXJkQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGgzPlRvcCBIZXJvZXM8L2gzPlxuPGRpdiBjbGFzcz1cImdyaWQgZ3JpZC1wYWRcIj5cbiAgICA8YSAqbmdGb3I9XCJsZXQgaGVybyBvZiBoZXJvZXNcIiBbcm91dGVyTGlua109XCJbJy9kZXRhaWwnLCBoZXJvLmlkXVwiIGNsYXNzPVwiY29sLTEtNFwiPlxuICAgICAgICA8ZGl2IGNsYXNzPVwibW9kdWxlIGhlcm9cIj5cbiAgICAgICAgICAgIDxoND57e2hlcm8ubmFtZX19PC9oND5cbiAgICAgICAgPC9kaXY+XG4gICAgPC9hPlxuPC9kaXY+XG48aGVyby1zZWFyY2g+PC9oZXJvLXNlYXJjaD4iLCI8ZGFzaGJvYXJkPjwvZGFzaGJvYXJkPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztNQ0VJO1FBQUE7UUFBQTtNQUFBO0lBQUE7TUFBQTtRQUFBO1FBQUE7UUFBQTtNQUFBOztNQUFBO1FBQUE7UUFBQTtRQUFBO01BQUE7O0lBQUE7T0FBQTtRQUFBO1FBQUE7TUFBQTtJQUFBO01BQUE7TUFBQTtRQUFBO1FBQUE7TUFBQTtNQUFBO0lBQUE7Z0JBQUE7Ozs7SUFBQTtPQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7Z0JBQStCO0lBQW9EO01BQy9FO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBeUI7SUFDckI7SUFBSTtNQUFBO01BQUE7SUFBQTtJQUFBO0lBQWtCO0lBQ3BCOzs7SUFIcUI7SUFBL0IsU0FBK0IsU0FBL0I7O0lBQUE7SUFBQTtJQUFBLFNBQUEsbUJBQUE7SUFFWTtJQUFBOzs7OztJQUpoQjtJQUFJO0lBQWU7TUFDbkI7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUEyQjtJQUN2QjtnQkFBQTs7OztJQUFBO09BQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUlJO0lBQ0Y7SUFDTjtnQkFBQTtnQkFBQTs7O0lBQUE7S0FBQTs7OztJQU5PO0lBQUgsU0FBRyxTQUFIO0lBTUo7Ozs7O0lDUkE7Z0JBQUE7OztJQUFBOzs7In0=
