/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */ export var styles = ['[class*=\'col-\'][_ngcontent-%COMP%] {\n    float: left;\n    padding-right: 20px;\n    padding-bottom: 20px;\n}\n\n[class*=\'col-\'][_ngcontent-%COMP%]:last-of-type {\n    padding-right: 0;\n}\n\na[_ngcontent-%COMP%] {\n    text-decoration: none;\n}\n\n*[_ngcontent-%COMP%], *[_ngcontent-%COMP%]:after, *[_ngcontent-%COMP%]:before {\n    -webkit-box-sizing: border-box;\n    -moz-box-sizing: border-box;\n    box-sizing: border-box;\n}\n\nh3[_ngcontent-%COMP%] {\n    text-align: center;\n    margin-bottom: 0;\n}\n\nh4[_ngcontent-%COMP%] {\n    position: relative;\n}\n\n.grid[_ngcontent-%COMP%] {\n    margin: 0;\n}\n\n.col-1-4[_ngcontent-%COMP%] {\n    width: 25%;\n}\n\n.module[_ngcontent-%COMP%] {\n    padding: 20px;\n    text-align: center;\n    color: #eee;\n    max-height: 120px;\n    min-width: 120px;\n    background-color: #607D8B;\n    border-radius: 2px;\n}\n\n.module[_ngcontent-%COMP%]:hover {\n    background-color: #EEE;\n    cursor: pointer;\n    color: #607d8b;\n}\n\n.grid-pad[_ngcontent-%COMP%] {\n    padding: 10px 0;\n}\n\n.grid-pad[_ngcontent-%COMP%] > [class*=\'col-\'][_ngcontent-%COMP%]:last-of-type {\n    padding-right: 20px;\n}\n\n@media (max-width: 600px) {\n    .module[_ngcontent-%COMP%] {\n        font-size: 10px;\n        max-height: 75px;\n    }\n}\n\n@media (max-width: 1024px) {\n    .grid[_ngcontent-%COMP%] {\n        margin: 0;\n    }\n    .module[_ngcontent-%COMP%] {\n        min-width: 60px;\n    }\n}'];
//# sourceMappingURL=dashboard.component.css.shim.ngstyle.js.map